### ISSUE TITLE
Java Stream의 Matching 부분에서...

### ISSUE THREAD

**Issue by seonghun127** [seongbeenkim/Java#1]
anyMatch, noneMatch, allMatch 등 Stream이 비어있을 경우 반환되는 값도 같이 정리하면 좋을 거 같아요~

**Comment by seongbeenkim** [comment]
@seonghun127 
성훈님 Stream이 비어있을 경우에 대한 내용 정리해서 추가했습니다~!
allMatch, noneMatch 같은 경우에는 vacuous truth때문에 true값이 반환된다고 나와있습니다. 근데 anyMatch는 false를 반환하길래 vacuous truth가 적용되지 않는가? 라고 해서 관련 글을 찾아보는데 빈 stream이기 때문에 어느 것도 매칭되는 것을 찾을 수 없어 false를 반환한다라는 글을 발견하였습니다.
위의 글의 내용이 맞다면 allMatch, noneMatch와는 다른 논리로 적용이 되는 것 같은데 이 부분에 대해서는 더 공부해보고 더 추가하겠습니다!

**Comment by seonghun127** [comment]
vacuous truth 공진리 명제에는 all이라는 개념이 들어가기 때문에 allMatch, nonoMatch에 vacuous truth가 적용되지만 anyMatch의 경우 명제 자체가 all 개념이 들어가지 않아서 false가 반환된다고 이해해도 좋겠네요 :)

**Comment by seongbeenkim** [comment]
all 개념으로 인해서 그런거였군요!! 감사합니다 :)
